
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 13;
  public static final int PUNTO = 2;
  public static final int RAIZ = 16;
  public static final int CADENA = 18;
  public static final int PYC = 4;
  public static final int CORC = 11;
  public static final int DIVIDIDO = 15;
  public static final int CORA = 10;
  public static final int PARC = 7;
  public static final int LLAVEC = 9;
  public static final int DOSP = 5;
  public static final int PARA = 6;
  public static final int LLAVEA = 8;
  public static final int POR = 14;
  public static final int ELEVADO = 17;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTO",
  "COMMA",
  "PYC",
  "DOSP",
  "PARA",
  "PARC",
  "LLAVEA",
  "LLAVEC",
  "CORA",
  "CORC",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "RAIZ",
  "ELEVADO",
  "CADENA"
  };
}

